INSERT INTO `sys_permissions` (`id`, `key`, `description`) VALUES
(1, 'dashboard_view', '대시보드 조회'),
(2, 'user_admin', '사용자 목록 조회 및 관리'),
(3, 'role_admin', '역할 및 퍼미션 관리'),
(4, 'employee_admin', '직원 정보 관리'),
(5, 'log_admin', '사용 로그 조회'),
(6, 'user_list_view', '전체 사용자 목록 조회'),
(8, 'littering_view', '부적정배출 조회'),
(9, 'littering_process', '부적정배출 처리 권한'),
(10, 'littering_manage', '부적정배출 관리 권한'),
(17, 'menu_admin', '메뉴 관리'),
(18, 'waste_admin', '인터넷배출 관리'),
(19, 'waste_view', '대형폐기물 수거 조회'),
(20, 'organization_admin', '부서 관리'),
(21, 'leave_admin', '연차 관리(부여, 승인 등)'),
(22, 'leave_view', '자신의 연차 내역 조회'),
(23, 'leave_request', '연차 신청'),
(24, 'holiday_admin', '휴일/근무일 설정 관리'),
(25, 'littering_admin', '부적정배출 관리자');
