INSERT INTO `sys_menus` (`id`, `parent_id`, `name`, `url`, `icon`, `permission_key`, `display_order`) VALUES
(100, NULL, '마이페이지', '/my-page', 'ri-dashboard-line', NULL, 10),
(200, NULL, '운행노선', '#', 'ri-route-line', '', 20),
(300, NULL, '대형폐기물', '/waste/index', 'ri-truck-line', 'waste.view', 30),
(301, 300, '대형폐기물 수거', '/waste/index', 'ri-truck-line', 'waste.view', 10),
(302, 300, '인터넷배출 관리', '/waste/manage', 'ri-global-line', 'waste.manage', 20),
(400, NULL, '무단투기 관리', '/littering/manage', 'ri-map-pin-user-line', 'littering.view', 40),
(401, 400, '무단투기 신고/처리', '/littering/index', 'ri-map-pin-add-line', 'littering.process', 10),
(402, 400, '검토 및 승인', '/littering/manage', 'ri-user-shared-line', 'littering.confirm', 20),
(403, 400, '처리 완료 내역', '/littering/history', 'ri-history-line', 'littering.view', 30),
(404, 400, '삭제된 항목', '/littering/deleted', 'ri-delete-bin-line', 'littering.restore', 40),
(900, NULL, '시스템 관리', '/employees', 'ri-settings-3-line', 'employee.view', 90),
(910, 900, '사용자/조직', '#', 'ri-team-line', '', 10),
(911, 910, '직원 관리', '/employees', 'ri-user-star-line', 'employee.view', 10),
(912, 910, '사용자 목록', '/admin/users', 'ri-user-3-line', 'user.view', 20),
(913, 910, '역할 및 권한', '/admin/role-permissions', 'ri-shield-user-line', 'role.assign_permissions', 30),
(914, 910, '부서/직급 관리', '/admin/organization', 'ri-building-4-line', 'organization.manage', 35),
(915, 910, '조직도', '/organization/chart', 'ri-node-tree', 'organization.view', 40),
(920, 900, '인사 관리', '#', 'ri-briefcase-4-line', '', 20),
(921, 920, '연차 부여/계산', '/leaves/granting', 'ri-user-add-line', 'leave.manage_entitlement', 10),
(922, 920, '연차 신청 승인', '/leaves/approval', 'ri-check-double-line', 'leave.approve', 20),
(923, 920, '직원 연차 내역', '/leaves/history', 'ri-user-search-line', 'leave.view_all', 30),
(924, 920, '휴일/근무일 설정', '/holidays', 'ri-calendar-2-line', 'holiday.manage', 40),
(930, 900, '사이트 관리', '#', 'ri-article-line', '', 30),
(931, 930, '공지사항 관리', '/admin/notices', 'ri-megaphone-line', NULL, 10), -- 'notice_admin' was not in the original list, so setting to NULL for now
(932, 930, '메뉴 관리', '/admin/menus', 'ri-menu-2-line', 'menu.manage', 20),
(940, 900, '시스템', '#', 'ri-server-line', '', 40),
(941, 940, '시스템 로그', '/logs', 'ri-file-text-line', 'log.view', 10);
