INSERT INTO `sys_menus` (`id`, `parent_id`, `name`, `url`, `icon`, `permission_key`, `display_order`) VALUES
(100, NULL, '메인', '/profile', 'ri-home-line', NULL, 10),
(101, 100, '대시보드', '/dashboard', 'ri-dashboard-line', 'dashboard_view', 10),
(102, 100, '내 정보', '/profile', 'ri-user-line', NULL, 20),
(103, 100, '연차 신청/내역', '/leaves/my', 'ri-calendar-check-line', 'leave_request', 30),
(200, NULL, '운행노선', '#', 'ri-route-line', '', 20),
(300, NULL, '대형폐기물', '/waste', 'ri-truck-line', 'waste_view', 30),
(301, 300, '대형폐기물 수거', '/waste', 'ri-truck-line', 'waste_view', 10),
(302, 300, '인터넷배출 관리', '/waste/admin', 'ri-global-line', 'waste_admin', 20),
(400, NULL, '무단투기 관리', '/littering/map', 'ri-map-pin-user-line', 'littering_process', 40),
(401, 400, '무단투기 신고/처리', '/littering/map', 'ri-map-pin-add-line', 'littering_process', 10),
(402, 400, '검토 및 승인', '/littering', 'ri-user-shared-line', 'littering_manage', 20),
(403, 400, '처리 완료 내역', '/littering/history', 'ri-history-line', 'littering_view', 30),
(404, 400, '삭제된 항목', '/littering/deleted', 'ri-delete-bin-line', 'littering_admin', 40),
(900, NULL, '시스템 관리', '/employees', 'ri-settings-3-line', 'employee_admin', 90),
(910, 900, '사용자/조직', '#', 'ri-team-line', '', 10),
(911, 910, '직원 관리', '/employees', 'ri-user-star-line', 'employee_admin', 10),
(912, 910, '사용자 목록', '/admin/users', 'ri-user-3-line', 'user_list_view', 20),
(913, 910, '역할 및 권한', '/admin/role-permissions', 'ri-shield-user-line', 'role_admin', 30),
(914, 910, '부서/직급 관리', '/admin/organization', 'ri-building-4-line', 'organization_admin', 40),
(920, 900, '인사 관리', '#', 'ri-briefcase-4-line', '', 20),
(921, 920, '연차 부여/계산', '/leaves/granting', 'ri-user-add-line', 'leave_admin', 10),
(922, 920, '연차 신청 승인', '/leaves/approval', 'ri-check-double-line', 'leave_admin', 20),
(923, 920, '직원 연차 내역', '/leaves/history', 'ri-user-search-line', 'leave_admin', 30),
(924, 920, '휴일/근무일 설정', '/holidays', 'ri-calendar-2-line', 'holiday_admin', 40),
(930, 900, '사이트 관리', '#', 'ri-article-line', '', 30),
(931, 930, '공지사항 관리', '/admin/notices', 'ri-megaphone-line', 'notice_admin', 10),
(932, 930, '메뉴 관리', '/admin/menus', 'ri-menu-2-line', 'menu_admin', 20),
(940, 900, '시스템', '#', 'ri-server-line', '', 40),
(941, 940, '시스템 로그', '/logs', 'ri-file-text-line', 'log_admin', 10);
